### ISSUE TITLE
Plugin incompatibility.

### ISSUE THREAD

**Issue by shitzuu** [casid/jte-intellij#1]
Hello, I'm user of jte plugin in my IntelliJ IDEA, is there chance of update to version 2020.3 which is EAP release?

**Comment by casid** [comment]
Hi @shitzuu, thanks for using jte and for reaching out!

I've adjusted the plugin so that there's no until build version set (https://github.com/casid/jte-intellij/commit/925bc3d3851f2901cf7198c670142adad3726eda).

I'm downloading the EAP version right now and will try if the plugin works. If so, I'll release an update of the plugin. It usually takes a few days until JetBrains approves it though. If you need it asap, you could probably build the plugin locally.

**Comment by shitzuu** [comment]
Okay, thanks for quick response I will try it.

**Comment by shitzuu** [comment]
Okay, I built this manually from the current repository and everything works, thank you again ;>

**Comment by casid** [comment]
Awesome! Looks good here as well, gonna publish the new version once I'm back at my MacBook.

**Comment by casid** [comment]
@shitzuu the plugin is published and pending JetBrains' approval.
