### ISSUE TITLE
Support for other Languages (IntelliJ)

### ISSUE THREAD

**Issue by Fleshgrinder** [casid/jte-intellij#11]
I'm searching for a template engine that I can integrate in Gradle to process files. `jte` and `kte` looks very nice because it supports everything Java or Kotlin supports, even extension methods. However, the IntelliJ file types are hardcoded for HTML and if I want to use it for templating in Helm, Terraform, `.properties`, YAML, ... (you name it) I have a problem. I know that IntelliJ offers the ability to overlay existing languages with templates, I also know that there is the plain formatter which would work here nicely.

There is of course much more to what I want to achieve but this would be the first required step to make this work. So, I'm posting here to see if there would be interest in supporting this?

What is much more? Basically the ability to automatically resolve things from Gradle's classpath and project so that one can access all extensions, properties, extra, ... without any additional configuration. This must be possible because IntelliJ can do it but no clue how...

**Comment by casid** [comment]
@Fleshgrinder I just transferred this issue to the jte IntelliJ plugin repository.

Currently this method controls what template data language is used (and defaults to HTML):

https://github.com/casid/jte-intellij/blob/571dad30c2d81436c066f0d6a83be43c9d85941d/src/main/java/org/jusecase/jte/intellij/language/JteFileViewProvider.java#L32

It looks like if there's a different mapping configured for a file it would use that instead of HTML:

```java
Language dataLang = TemplateDataLanguageMappings.getInstance(manager.getProject()).getMapping(file);
if (dataLang == null) {
    dataLang = HtmlFileType.INSTANCE.getLanguage();
}
```

I never used that though, but might be a starting point to look at.
