### ISSUE TITLE
Enable JTE template as language injection

### ISSUE THREAD

**Issue by jankod** [casid/jte-intellij#14]
It would be good if the JTE template could be used as an injection language. New java has the ability to work with muliline string.

**Comment by casid** [comment]
I'm not sure if this will work, since jte itself makes heavy use of language injection for the Java / Kotlin code parts.

Is there a usecase (except from unit tests) to pass templates as Java Strings to the engine?

**Comment by jankod** [comment]
I had an idea to make a small component framework on top of JTE. New java now has the possibility of a multiline string, so it can be cool that the template and the model should be in one file (as Vue or Angular).

**Comment by casid** [comment]
That's interesting. Do you already have something implemented? With jte I started with the engine and did the IntelliJ plugin last. The plugin was more work than the engine :-D I'm asking, because you might end up with your own file extension to put all this data to (like *.vue). This would probably result in a separate IntelliJ plugin that uses the jte plugin language for defined sections.

**Comment by jankod** [comment]
I don't have anything concrete yet, I'm just developing a concept for small framework for fast prototyping web pages. 
For now, I was hoping to get something functional like below code . I think JTE would be better than FreeMarker for this case. FreeMarker has good code completion in Idea, but it is hard to automatically escape components and syntax is complex.


```java
@Slf4j
@Getter
@Route("/")
public class IndexPage extends Page {

    private Button button;
    private TodoForm form;

    public IndexPage() {
        button = new Button("Button 1");
        button.onClick(this::clickButton);
        form = new TodoForm();
    }

    public void clickButton(WebooRequest r) {
        button.setLabel("clicked");
    }

    @Override
    @Language("InjectedFreeMarker")
    public String render() {
        return """
                <div class='card'>
                Index page                
                ${button}                
                </div>
                """;
    }
}
```

**Comment by casid** [comment]
Oh I see. Imo there are a few disadvantages of using Strings for templates like this:
- No real hot reload for templates, you need to recompile the class
- Template Strings in larger projects use a lot of memory of the constant pool
- Precompiling templates as part of the build process will become difficult
- Users could do weird hacks - since the template is just a String you could create it with a StringBuilder or other unkown mechanisms

Would this be for server side rendering only, or do you plan to also add some JS interactivity?

**Comment by jankod** [comment]
You are absolutely right, there are actually more problems to solve. 
Recompiling the class is not problem in debug mode, usually it's just hot swap, especially it is fast in Eclipse.
It is not framework for large project, it’s more for a fast prototype, no need for turbo speed..  So maybe make components on the bootstrap css framework, to quickly work with forms and tables with pagination. Something like Vaadin and Wicket, but lightway, for developers who don't know much about css and javascript.
In my case, 95% of projects are typical business application for small users with lots of forms and tables.
It will be server side rendering with built-in javascript. 
Now I'm playing with a combination of j2html with Htmx, and I am looking for a concept that could satisfy all of the above.

Java has a lot of technology for large enterprise projects, but not for small projects.
PHP Symfony and Python Django has a great form builder, that is missing in Java.

I like JTE because it's like java + html. No need to learn new syntax.

**Comment by casid** [comment]
My jte setup right now is quite similiar. I have Page objects containing all data the template needs, but the Page has an abstract method to provide the template path. The jte IntelliJ plugin allows to ctrl+click on ".jte" Strings to automatically jump to the template.

```java
    @Override
    public String getTemplate() {
        return "index.jte";
    }
```

It is still one indirection, though.

I just thought about your button component... Doing this as a new file format in the spirit of Svelte or Vue would look something like this:

```
class Button {
    String title;
}

<button>${title}</button>
```

This could be compiled to something implementing `gg.jte.Content` so that it can be included in other pages. I really haven't thought this through, but maybe this goes in the direction you're after.
