### ISSUE TITLE
Pattern match doesn't get syntax highlight with @elseif

### ISSUE THREAD

**Issue by renannprado** [casid/jte-intellij#15]
As you can see in the screenshot, the first `@if` gets syntax highlight/autocomplete support, but the `@elseif` doesn't. Trying to use a different variable name in the `@elseif` also doesn't help.

![image](https://user-images.githubusercontent.com/2359543/146609812-28f87cf6-dbda-4bce-99e9-1e11300c525e.png)

```html
@for(var x : fields)
    <label>${x.name()}</label>
    @if(x instanceof FreeTextInputConfig field)
        <input name="${field.name()}" type="text"
                       value="${field.defaultValue().orElse("")}"/><br/>
    @elseif(x instanceof MultiChoiceInputConfig field)
        <input name="${field.name()}" type="checkbox"
               value="${field.defaultValue().orElse("")}"/><br/>
    @endif
@endfor
```

**Comment by casid** [comment]
Sorry for the late reply, and thanks for reporting this.

I'm a little bit embarresed about this fix :-/

**Comment by casid** [comment]
I just published a new plugin version (1.5.1), including this fix.

Sorry again, for the long delay and the inconvenience!

**Comment by renannprado** [comment]
@casid does it take some time for IntelliJ to update the marketplace with the update? I don't have the option to update to `1.5.1`.

**Comment by casid** [comment]
@renannprado yes, all new versions are reviewed by JetBrains after upload, before they are released.

> All new updates are normally reviewed within two business days. You will receive a notification as soon as status of this review changes.

I think it should be available tomorrow.

**Comment by Masterzach32** [comment]
Hi there, I'm on 1.5.1 and getting a similar issue with .kte templates. First @if gets syntax highlighting and smart-casting, however the @elseif blocks do not, and hovering over the variable shows no documentation found. I've attached an example project: https://github.com/Masterzach32/jte-example, as well as an image:

![image](https://user-images.githubusercontent.com/4240699/154367782-186a1c7f-cae0-4f16-afbf-a219a425652c.png)

Despite this, the template still compiles and provides the expected result (will print value of y, z1 and z2). In addition, IntelliJ freezes for ~second when typing or running inspections in the template. My example class hierarchy is a simplified version from a project I'm working on where this bug is causing IntelliJ to hang for several seconds whenever I create a new html tag, jte @for/@if statement, or ${} block.

In the example project, I commented out the affected jte code and added a replacement @if statement that doesn't use @elseif, and provides the same output and has full syntax highlighting and autocomplete.

**Comment by Masterzach32** [comment]
@casid looks like the same bug is present in `KteKotlinLanguageInjector.java`?

https://github.com/casid/jte-intellij/blob/master/src/main/java/org/jusecase/jte/intellij/language/KteKotlinLanguageInjector.java#L183

**Comment by casid** [comment]
@Masterzach32 yes, indeed. Dang, sorry that I didn't think about this one the initial fix!

Will commit a fix tonight after work.

**Comment by casid** [comment]
Pushed the fix! Probably gonna publish a new plugin version this weekend, together with jte 2.

**Comment by Masterzach32** [comment]
Awesome, thank you!

**Comment by casid** [comment]
@Masterzach32 the new plugin version got approved by Jetbrains, containing this fix.

Beware: Using the latest plugin version requires an update to jte 2: https://github.com/casid/jte/releases/tag/2.0.0

The migration is all automatic and shouldn't take longer than a few minutes, though.
