### ISSUE TITLE
Alternate suffixes from IntelliJ's file types should be respected by @template

### ISSUE THREAD

**Issue by stepbeekio** [casid/jte-intellij#23]
# Context

We use the[ tailwind intellij plugin](https://plugins.jetbrains.com/plugin/15321-tailwind-css) which can be temperamental at times. I cannot figure out how to get the plugin to recognize kte files, even when moving the kte directory into the node.js project directory.

The workaround that I've discovered is to use a *.kte.html suffix for the template files. While this enables tailwind autocomplete, it breaks the @template utility in JTE. 

# Proposed Fix

Since the tailwind plugin for intellij is closed source, I would like to propose allowing the JTE intellij plugin to accept overrides for the file suffixes that it uses for platform autocomplete. This is consistent with the core template engine allowing users to override the suffix they're using (e.g. in the spring boot starter's JteProperties). There are a handful of other places in this plugin where ".kte" and ".jte" are hardcoded. 

I'm not well-versed enough in the IntelliJ platform API to know if we could fetch this directly from Settings | Editor | File Types for the KTE and JTE types, or whether it would need a new settings menu.

I'm going to take a run at this to submit a pull request for you to review if interested @casid. If worthwhile in the case of @template completions, then I'll follow up with a pull request to apply this change more generally to the plugin.

**Comment by casid** [comment]
Welcome @stepbeekio! I'm afraid this would also require changes to the template engine itself first, like [here](https://github.com/casid/jte/blob/b1f7bfecb90ed20999fd57ddacc6e2cfa8cc47fd/jte/src/main/java/gg/jte/compiler/IoUtils.java#L52) or [here](https://github.com/casid/jte/blob/b1f7bfecb90ed20999fd57ddacc6e2cfa8cc47fd/jte/src/main/java/gg/jte/compiler/ClassDefinition.java#L16). Of course, this can be changed to be parameterizable, but adds some extra complexity, instead of relying on conventions.

Maybe, it would be possible to ask the tailwind plugin to enable their processing for jte/kte files as well? They probably have made some additions already, like JSP for example.

**Comment by stepbeekio** [comment]
Ah, fair enough! I don't think I can commit to supporting any change like that so it would be pretty unfair of me to try to submit a pull request before disappearing. 

Thanks for the rapid response @casid! I'll post an issue to JetBrains then link it here in a closing comment for anyone else who runs into this issue.

**Comment by stepbeekio** [comment]
JetBrains tracker issue opened: https://youtrack.jetbrains.com/issue/IDEA-311345/Support-.jte-and-.kte-files-in-the-tailwind-plugin-for-IntelliJ

If anyone else is interested in this, then please upvote that ticket. @casid I'm going to close this issue since there's no action on the jte-intellij side. Thanks again for the help - and the very easy to understand plugin code!

**Comment by casid** [comment]
Thank you. Funny, I just stumbled upon your reddit post :-) I also left an upvote on the Jetbrains ticket.
