### ISSUE TITLE
auto import do not get the @ prefix in .kte

### ISSUE THREAD

**Issue by syzsh** [casid/jte-intellij#24]
插件版本: 2.0.8

在`.kte`格式模板中, 导入jdk类时, 缺少@前缀

![企业微信截图_16752551934054](https://user-images.githubusercontent.com/7196606/216044963-2059e30b-99a7-4a1d-bdc1-234fe4d2d26c.png)

![image](https://user-images.githubusercontent.com/7196606/216046057-dee83702-6635-4370-ab56-f1b41fb30c58.png)

导入第三方jar中的类, 还会导致这样的问题:

![image](https://user-images.githubusercontent.com/7196606/216048169-6cf7cc3e-9ceb-41f1-94e5-ef075cc7083c.png)

![image](https://user-images.githubusercontent.com/7196606/216048221-6cc7b72f-1469-4156-99e7-2826db4820b5.png)

**Comment by casid** [comment]
Thanks for reporting! It will probably take a few weeks until I can look into this.

In case anyone wants to have a look, this is probably due to:
`org.jusecase.jte.intellij.language.KteKotlinContentManipulator`

I think I rushed this when adding Kotlin support, and there's even a leftover TODO in `org.jusecase.jte.intellij.language.KteKotlinContentManipulator#isRequiredToOptimizeImports`.

**Comment by casid** [comment]
@syzsh I didn't sleep well tonight and had a look at it, I think this is fixed by https://github.com/casid/jte-intellij/commit/4fc6cb3c2fdfe3a96f3e45d81f399ce700c3ad21.

**Comment by casid** [comment]
@syzsh I just uploaded version `2.0.9` to the Jetbrains Marketplace, which includes this fix. Usually this gets reviewed and approved within two working days.

**Comment by syzsh** [comment]
@casid 非常感谢，辛苦了~
